version: "3.7"

services:
  reverse-proxy:
    image: "nginx:week-mates"
    build:
      context: "./"
      dockerfile: "Dockerfile.reverse-proxy"
    container_name: "week-mates-reverse-proxy"
    volumes:
      - "./nginx/certs:/etc/nginx/certs"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
    networks:
      week-mates-network:
        ipv4_address: "172.10.0.2"

  api-server:
    image: "dotnet-core-sdk:week-mates"
    build:
      context: "./"
      dockerfile: "Dockerfile.api-server"
    container_name: "week-mates-api-server"
    env_file:
      - "./.env"
    volumes:
      - "./WeekMates:/var/www/WeekMates"
    expose:
      - "5000"
    networks:
      week-mates-network:
        ipv4_address: "172.10.0.3"

  swagger:
    image: "swaggerapi/swagger-editor"
    container_name: "week-mates-swagger-editor"
    environment:
      URL: "/var/swagger/swagger.yml"
    volumes:
      - "./swagger:/var/www/swagger"
    expose:
      - "8080"
    networks:
      week-mates-network:
        ipv4_address: "172.10.0.4"

networks:
  week-mates-network:
    name: "week-mates-network"
    ipam:
      config:
        - subnet: "172.10.0.0/24"

