version: "3.7"

services:
  reverse-proxy:
    image: "nginx:week-mates"
    build:
      context: "./"
      dockerfile: "Dockerfile.reverse-proxy"
    container_name: "week-mates-reverse-proxy"
    volumes:
      - "./nginx/certs:/etc/nginx/certs"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
    networks:
      week-mates-network:
        ipv4_address: "172.10.0.2"

  server:
    image: "dotnet-core-sdk:week-mates"
    build:
      context: "./"
      dockerfile: "Dockerfile.server"
    container_name: "week-mates-server"
    env_file:
      - "./.env"
    volumes:
      - "./WeekMates:/var/www/WeekMates"
    expose:
      - "5000"
    networks:
      week-mates-network:
        ipv4_address: "172.10.0.3"

networks:
  week-mates-network:
    name: "week-mates-network"
    ipam:
      config:
        - subnet: "172.10.0.0/24"

